AWSTemplateFormatVersion: 2010-09-09
Resources:
  VanityNumbersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'CallerNumber'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'CallerNumber'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: VanityNumber
  ContactFlowTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'Version'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Version'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ContactFlow
  VanityNumberFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'vanity-num-generator'
      Handler: index.handler
      Runtime: nodejs12.x
      Code:
        ZipFile: true;
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Timeout: '30'
    DependsOn:
      - LambdaExecutionRole
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
                Effect: Allow
              - Action:
                  - 'dynamodb:PutItem'
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  GenerateContactFlowFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'contact-flow-gen'
      Runtime: nodejs12.x
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Handler: index.handler
      Code:
        ZipFile: |
          let aws = require('aws-sdk');
          let response = require('cfn-response');
          exports.handler = function(event, context) {
              console.log("REQUEST RECEIVED:\n" + JSON.stringify(event))
              let responseData = {};
              let lambdaArn =  event.ResourceProperties.VanityNumbersArn;
              responseData.lambdaArn = lambdaArn;
              responseData.contactFlowJson = {"modules":[{"id":"431f29e2-cca7-44e4-a449-90a38c2d327b","type":"PlayPrompt","branches":[{"condition":"Success","transition":"96f62f74-1905-40cd-acca-714c0782717a"}],"parameters":[{"name":"Text","value":"Sorry, we failed to create vanity numbers for your number. Please try again.","namespace":null},{"name":"TextToSpeechType","value":"text"}],"metadata":{"position":{"x":572,"y":278},"useDynamic":false}},{"id":"96f62f74-1905-40cd-acca-714c0782717a","type":"Disconnect","branches":[],"parameters":[],"metadata":{"position":{"x":874,"y":227}}},{"id":"7329da0c-3dcb-4661-a72e-95b6e841a4a4","type":"PlayPrompt","branches":[{"condition":"Success","transition":"96f62f74-1905-40cd-acca-714c0782717a"}],"parameters":[{"name":"Text","value":"$.External.responseMessage\n\nRepeating, your vanity numbers are:\n$.External.responseMessage","namespace":null},{"name":"TextToSpeechType","value":"text"}],"metadata":{"position":{"x":560,"y":118},"useDynamic":false}},{"id":"7eefafd6-402f-4759-967c-b017ef5f3969","type":"InvokeExternalResource","branches":[{"condition":"Success","transition":"7329da0c-3dcb-4661-a72e-95b6e841a4a4"},{"condition":"Error","transition":"431f29e2-cca7-44e4-a449-90a38c2d327b"}],"parameters":[{"name":"FunctionArn","value":lambdaArn,"namespace":null},{"name":"TimeLimit","value":"8"}],"metadata":{"position":{"x":288,"y":162},"dynamicMetadata":{},"useDynamic":false},"target":"Lambda"},{"id":"4d36a741-bc87-4035-b3fa-9c8390e687ac","type":"PlayPrompt","branches":[{"condition":"Success","transition":"7eefafd6-402f-4759-967c-b017ef5f3969"}],"parameters":[{"name":"Text","value":"Thanks for calling the AJD VoiceFoundry vanity number generation hotline!  \n\nNow we will use AWS Lambda to generate a few vanity numbers based on your incoming phone number.  These will preserve your area code, and use the rest of your phone number to generate mneumonics based on your number. \n\nNow calling AWS Lambda to generate your numbers.","namespace":null},{"name":"TextToSpeechType","value":"text"}],"metadata":{"position":{"x":44,"y":168},"useDynamic":false}}],"version":"1","type":"contactFlow","start":"4d36a741-bc87-4035-b3fa-9c8390e687ac","metadata":{"entryPointPosition":{"x":15,"y":15},"snapToGrid":false,"name":"new1","description":"Invokes a lambda function to determine information about the user.","type":"contactFlow","status":"saved","hash":"3b33c048f17897c0b18c990bc5bb703479c5c3456846127116d7088b7b1941a3"}}
              const docClient = new aws.DynamoDB.DocumentClient();
              let saveObject = {
                'Version': 'Latest',
                'ContactFlowJson': JSON.stringify(responseData.contactFlowJson),
              }
              let params = {
                TableName: 'ContactFlow',
                Item: saveObject,
              }
              docClient.put(params, function(err, data) {
                if (err) {
                  console.log("Error", err);
                } else {
                  console.log("Success", data);
                }
              });
              response.send(event, context, 'SUCCESS', responseData);
          }
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active
    DependsOn:
      - LambdaExecutionRole
      - ContactFlowTable
  GenerateContactFlow:
    Type: Custom::GenerateContactFlow
    Properties:
      ServiceToken:
        !GetAtt
        - GenerateContactFlowFunction
        - Arn
      VanityNumbersArn:
        !GetAtt
        - VanityNumberFunction
        - Arn
    DependsOn:
      - GenerateContactFlowFunction